(function () {
  const t = (es, en, fr) => ({ es, en, fr });
  const allergenNotice = t(
    "Alérgenos orientativos: confirma siempre con el personal antes de pedir.",
    "Indicative allergens: always confirm with the team before ordering.",
    "Allergènes indicatifs : confirmez toujours avec l’équipe avant de commander.",
  );
  const allergen = (es, en, fr) => t(es, en, fr);
  const allergenSets = {
    none: allergen("Ninguno declarado", "None declared", "Aucun déclaré"),
    gluten: allergen("Gluten", "Gluten", "Gluten"),
    glutenFree: allergen("Sin gluten", "Gluten-free", "Sans gluten"),
    glutenOption: allergen("Opción sin gluten", "Gluten-free option", "Option sans gluten"),
    egg: allergen("Huevo", "Egg", "Œuf"),
    dairy: allergen("Lácteos", "Dairy", "Produits laitiers"),
    fish: allergen("Pescado", "Fish", "Poisson"),
    molluscs: allergen("Moluscos", "Molluscs", "Mollusques"),
    crustaceans: allergen("Crustáceos", "Crustaceans", "Crustacés"),
    nuts: allergen("Frutos de cáscara", "Tree nuts", "Fruits à coque"),
    sulphites: allergen("Sulfitos", "Sulphites", "Sulfites"),
    glutenMolluscs: allergen("Gluten · Moluscos", "Gluten · Molluscs", "Gluten · Mollusques"),
    glutenDairy: allergen("Gluten · Lácteos", "Gluten · Dairy", "Gluten · Produits laitiers"),
    glutenEgg: allergen("Gluten · Huevo", "Gluten · Egg", "Gluten · Œuf"),
    glutenEggDairy: allergen("Gluten · Huevo · Lácteos", "Gluten · Egg · Dairy", "Gluten · Œuf · Produits laitiers"),
    glutenOptionEgg: allergen("Opción sin gluten · Huevo", "Gluten-free option · Egg", "Option sans gluten · Œuf"),
    glutenOptionEggDairy: allergen("Opción sin gluten · Huevo · Lácteos", "Gluten-free option · Egg · Dairy", "Option sans gluten · Œuf · Produits laitiers"),
    eggDairy: allergen("Huevo · Lácteos", "Egg · Dairy", "Œuf · Produits laitiers"),
    eggDairyNuts: allergen("Huevo · Lácteos · Frutos de cáscara", "Egg · Dairy · Tree nuts", "Œuf · Produits laitiers · Fruits à coque"),
    dairyNuts: allergen("Lácteos · Frutos de cáscara", "Dairy · Tree nuts", "Produits laitiers · Fruits à coque"),
    fishEgg: allergen("Pescado · Huevo", "Fish · Egg", "Poisson · Œuf"),
    glutenFishEgg: allergen("Gluten · Pescado · Huevo", "Gluten · Fish · Egg", "Gluten · Poisson · Œuf"),
    fishGlutenFree: allergen("Pescado · Sin gluten", "Fish · Gluten-free", "Poisson · Sans gluten"),
    glutenEggMolluscs: allergen("Gluten · Huevo · Moluscos", "Gluten · Egg · Molluscs", "Gluten · Œuf · Mollusques"),
    glutenCrustaceansEgg: allergen("Gluten · Crustáceos · Huevo", "Gluten · Crustaceans · Egg", "Gluten · Crustacés · Œuf"),
    glutenEggDairyFish: allergen("Gluten · Huevo · Lácteos · Pescado", "Gluten · Egg · Dairy · Fish", "Gluten · Œuf · Produits laitiers · Poisson"),
  };

  window.cartaData = {
    defaultLanguage: "es",
    languages: [
      { code: "es", label: "ES", name: "Español" },
      { code: "en", label: "EN", name: "English" },
      { code: "fr", label: "FR", name: "Français" },
    ],
    ui: {
      kicker: t("La carta", "À la carte", "La carte"),
      title: t("La carta", "À la carte", "La carte"),
      stamp: t("Desde Pamplona", "From Pamplona", "Depuis Pampelune"),
      categoriesLabel: t("Categorías de la carta", "À la carte categories", "Catégories de la carte"),
      categoryLabel: t("Sección", "Section", "Section"),
      special: t("Especialidad Casa Paco", "Casa Paco speciality", "Spécialité Casa Paco"),
      recommended: t("Recomendado", "Recommended", "Recommandé"),
      moreInfo: t("Más información", "More information", "Plus d’informations"),
      description: t("Descripción", "Description", "Description"),
      ingredients: t("Ingredientes", "Ingredients", "Ingrédients"),
      allergens: t("Alérgenos", "Allergens", "Allergènes"),
      close: t("Cerrar", "Close", "Fermer"),
      tagline: t("De nuestra cocina a tu mesa.", "From our kitchen to your table.", "De notre cuisine à votre table."),
      note: t(
        "Precios con IVA incluido. Servicio de terraza: +1 €. Avisa al personal de cualquier alergia o intolerancia.",
        "Prices include VAT. Terrace service: +€1. Tell the team about any allergy or intolerance.",
        "Prix TTC. Service en terrasse : +1 €. Signalez toute allergie ou intolérance à l’équipe.",
      ),
    },
    categories: [
      {
        id: "picoteo",
        number: "01",
        label: t("Picoteo", "To share", "À partager"),
        title: t("Picoteo y clásicos", "Bites and classics", "À partager et classiques"),
        dishes: [
          {
            id: "bravas",
            name: t("Bravas", "Patatas bravas", "Patatas bravas"),
            price: "9 €",
            description: t("Caseras con nuestra salsa.", "Homemade, served with our house sauce.", "Maison, servies avec notre sauce."),
            ingredients: t("Patata · salsa de la casa", "Potato · house sauce", "Pomme de terre · sauce maison"),
            allergens: allergenNotice,
            image: null,
          },
          {
            id: "rabas-chipiron",
            name: t("Rabas de chipirón", "Baby squid strips", "Lamelles de petit calamar"),
            price: "11 €",
            description: t("Con ralladura de lima.", "With lime zest.", "Avec zestes de citron vert."),
            ingredients: t("Chipirón · lima", "Baby squid · lime", "Petit calamar · citron vert"),
            allergens: allergenNotice,
            image: null,
          },
          {
            id: "chopitos",
            name: t("Chopitos", "Baby squid", "Petits calamars"),
            price: "10 €",
            description: t("Con pimientos de Padrón.", "With Padrón peppers.", "Avec piments de Padrón."),
            ingredients: t("Chopitos · pimientos de Padrón", "Baby squid · Padrón peppers", "Petits calamars · piments de Padrón"),
            allergens: allergenNotice,
            image: null,
          },
          {
            id: "padron",
            name: t("Padrón", "Padrón peppers", "Piments de Padrón"),
            price: "8 €",
            description: t("Con escamas de sal.", "With salt flakes.", "Avec fleur de sel."),
            ingredients: t("Pimientos de Padrón · sal", "Padrón peppers · salt", "Piments de Padrón · sel"),
            allergens: allergenNotice,
            image: null,
          },
          {
            id: "jamon-iberico",
            name: t("Jamón ibérico", "Iberian ham", "Jambon ibérique"),
            price: "20 €",
            description: t("Con tostones y AOVE.", "With toasted bread and extra virgin olive oil.", "Avec pain grillé et huile d’olive vierge extra."),
            ingredients: t("Jamón ibérico · pan tostado · AOVE", "Iberian ham · toasted bread · EVOO", "Jambon ibérique · pain grillé · huile d’olive"),
            allergens: allergenNotice,
            image: null,
          },
          {
            id: "chistorra",
            name: t("Chistorra de Arrieta", "Arrieta chistorra", "Chistorra d’Arrieta"),
            price: "11 €",
            description: t("Chistorra de Arrieta.", "Chistorra from Arrieta.", "Chistorra d’Arrieta."),
            ingredients: t("Chistorra", "Chistorra sausage", "Saucisse chistorra"),
            allergens: allergenNotice,
            image: null,
          },
        ],
      },
      {
        id: "principales",
        number: "02",
        label: t("Principales", "Main dishes", "Plats"),
        title: t("Platos principales", "Main dishes", "Plats principaux"),
        dishes: [
          {
            id: "ajoarriero",
            name: t("Ajoarriero", "Ajoarriero cod", "Morue ajoarriero"),
            price: "18 €",
            description: t("Con huevo a baja temperatura y patatas paja.", "With slow-cooked egg and shoestring potatoes.", "Avec œuf basse température et pommes paille."),
            ingredients: t("Bacalao · huevo · patatas paja", "Cod · egg · shoestring potatoes", "Morue · œuf · pommes paille"),
            allergens: allergenNotice,
            image: null,
          },
          {
            id: "callos",
            name: t("Callos tradicionales", "Traditional tripe", "Tripes traditionnelles"),
            price: "17 €",
            description: t("Al estilo tradicional.", "Traditional style.", "Préparées dans la tradition."),
            ingredients: t("Callos · salsa tradicional", "Tripe · traditional sauce", "Tripes · sauce traditionnelle"),
            allergens: allergenNotice,
            badge: "recommended",
            image: null,
          },
          {
            id: "rabo-estofado",
            name: t("Rabo estofado", "Braised oxtail", "Queue de bœuf braisée"),
            price: "20 €",
            description: t("Al vino tinto con patatas fritas caseras.", "Braised in red wine with homemade fries.", "Braisée au vin rouge avec frites maison."),
            ingredients: t("Rabo · vino tinto · patatas", "Oxtail · red wine · potatoes", "Queue de bœuf · vin rouge · pommes de terre"),
            allergens: allergenNotice,
            badge: "special",
            image: null,
          },
          {
            id: "manitas",
            name: t("Manitas crujientes", "Crispy pig’s trotters", "Pieds de porc croustillants"),
            price: "19 €",
            description: t("Crujientes con patatas fritas caseras.", "Crispy, with homemade fries.", "Croustillants, avec frites maison."),
            ingredients: t("Manitas de cerdo · patatas", "Pig’s trotters · potatoes", "Pieds de porc · pommes de terre"),
            allergens: allergenNotice,
            badge: "recommended",
            image: null,
          },
          {
            id: "entrecot",
            name: t("Entrecot de vaca", "Beef entrecôte", "Entrecôte de bœuf"),
            price: "20 €",
            description: t("Con pimientos de Padrón y patatas fritas caseras.", "With Padrón peppers and homemade fries.", "Avec piments de Padrón et frites maison."),
            ingredients: t("Entrecot · pimientos de Padrón · patatas", "Beef entrecôte · Padrón peppers · potatoes", "Entrecôte · piments de Padrón · pommes de terre"),
            allergens: allergenNotice,
            badge: "special",
            image: null,
          },
          {
            id: "chipirones-pelayo",
            name: t("Chipirones a lo Pelayo", "Pelayo-style baby squid", "Petits calamars à la Pelayo"),
            price: "18 €",
            description: t("Con patatas panaderas.", "With sliced baked potatoes.", "Avec pommes de terre boulangères."),
            ingredients: t("Chipirones · cebolla · patatas", "Baby squid · onion · potatoes", "Petits calamars · oignon · pommes de terre"),
            allergens: allergenNotice,
            image: null,
          },
          {
            id: "pescado-fresco",
            name: t("Pescado fresco del día", "Fresh fish of the day", "Poisson frais du jour"),
            price: "17 €",
            description: t("Variedad a consultar.", "Ask about today’s selection.", "Variété du jour à consulter."),
            ingredients: t("Pescado fresco del día", "Fresh fish of the day", "Poisson frais du jour"),
            allergens: allergenNotice,
            image: null,
          },
        ],
      },
      {
        id: "ensaladas",
        number: "03",
        label: t("Ensaladas", "Salads", "Salades"),
        title: t("Ensaladas", "Salads", "Salades"),
        dishes: [
          {
            id: "ensalada-mixta",
            name: t("Mixta estilo Casa Paco", "Casa Paco mixed salad", "Salade mixte Casa Paco"),
            price: t("11 € · Media 7 €", "€11 · Half €7", "11 € · Demi 7 €"),
            description: t("Ensalada mixta estilo Casa Paco.", "Casa Paco-style mixed salad.", "Salade mixte façon Casa Paco."),
            ingredients: t("Ingredientes a consultar", "Ask about ingredients", "Ingrédients à consulter"),
            allergens: allergenNotice,
            image: null,
          },
          {
            id: "ensalada-chopitos",
            name: t("Ensalada de chopitos", "Baby squid salad", "Salade de petits calamars"),
            price: t("13 € · Media 8 €", "€13 · Half €8", "13 € · Demi 8 €"),
            description: t("Con cebolla crujiente y alioli.", "With crispy onion and aioli.", "Avec oignon croustillant et aïoli."),
            ingredients: t("Ensalada · chopitos · cebolla crujiente · alioli", "Salad · baby squid · crispy onion · aioli", "Salade · petits calamars · oignon croustillant · aïoli"),
            allergens: allergenNotice,
            image: null,
          },
          {
            id: "ensalada-cabra",
            name: t("Ensalada de queso de cabra", "Goat’s cheese salad", "Salade au chèvre"),
            price: t("13 € · Media 8 €", "€13 · Half €8", "13 € · Demi 8 €"),
            description: t("Con confituras y frutos.", "With preserves and fruit.", "Avec confitures et fruits."),
            ingredients: t("Ensalada · queso de cabra · confituras · frutos", "Salad · goat’s cheese · preserves · fruit", "Salade · chèvre · confitures · fruits"),
            allergens: allergenNotice,
            image: null,
          },
        ],
      },
      {
        id: "huevos",
        number: "04",
        label: t("Huevos", "Eggs", "Œufs"),
        title: t("Huevos", "Eggs", "Œufs"),
        dishes: [
          {
            id: "huevos-foie",
            name: t("Huevos fritos con AOVE", "Fried eggs with EVOO", "Œufs frits à l’huile d’olive"),
            price: "14 €",
            description: t("Con foie, trufa rallada y patatas fritas caseras.", "With foie gras, grated truffle and homemade fries.", "Avec foie gras, truffe râpée et frites maison."),
            ingredients: t("Huevos · AOVE · foie · trufa · patatas", "Eggs · EVOO · foie gras · truffle · potatoes", "Œufs · huile d’olive · foie gras · truffe · pommes de terre"),
            allergens: allergenNotice,
            image: null,
          },
          {
            id: "huevos-patatas",
            name: t("Huevos con patatas caseras", "Eggs with homemade fries", "Œufs avec frites maison"),
            price: "11 €",
            description: t(
              "A elegir: chistorra, magras, lomo, panceta, jamón o pechuga.",
              "Choose from chistorra, pork, loin, bacon, ham or chicken breast.",
              "Au choix : chistorra, porc, longe, poitrine, jambon ou blanc de poulet.",
            ),
            ingredients: t(
              "Huevos · patatas · acompañamiento a elegir",
              "Eggs · potatoes · choice of topping",
              "Œufs · pommes de terre · accompagnement au choix",
            ),
            allergens: allergenNotice,
            image: null,
          },
        ],
      },
      {
        id: "fritos",
        number: "05",
        label: t("Fritos", "Fried bites", "Fritures"),
        title: t("Fritos caseros", "Homemade fried bites", "Fritures maison"),
        dishes: [
          {
            id: "croqueta-jamon",
            name: t("Croqueta de jamón y huevo", "Ham and egg croquette", "Croquette jambon et œuf"),
            price: "2,70 €",
            description: t("Croqueta de jamón y huevo.", "Ham and egg croquette.", "Croquette au jambon et à l’œuf."),
            ingredients: t("Jamón · huevo", "Ham · egg", "Jambon · œuf"),
            allergens: allergenNotice,
            image: null,
          },
          {
            id: "frito-jamon-queso",
            name: t("Frito de jamón york y queso", "Ham and cheese fritter", "Beignet jambon-fromage"),
            price: "2,70 €",
            description: t("Frito casero de jamón york y queso.", "Homemade ham and cheese fritter.", "Beignet maison au jambon et fromage."),
            ingredients: t("Jamón york · queso", "Ham · cheese", "Jambon · fromage"),
            allergens: allergenNotice,
            image: null,
          },
          {
            id: "frito-pimiento",
            name: t("Frito de pimiento", "Pepper fritter", "Beignet au poivron"),
            price: "2,70 €",
            description: t("Con un toque picante.", "With a spicy touch.", "Avec une touche relevée."),
            ingredients: t("Pimiento", "Pepper", "Poivron"),
            allergens: allergenNotice,
            image: null,
          },
          {
            id: "frito-calamar",
            name: t("Frito de calamar", "Squid fritter", "Beignet de calamar"),
            price: "2,90 €",
            description: t("Frito casero de calamar.", "Homemade squid fritter.", "Beignet maison au calamar."),
            ingredients: t("Calamar", "Squid", "Calamar"),
            allergens: allergenNotice,
            image: null,
          },
          {
            id: "frito-gamba",
            name: t("Frito de gamba", "Prawn fritter", "Beignet de crevette"),
            price: "2,70 €",
            description: t("En un vasito con alioli.", "Served in a small glass with aioli.", "Servi en verrine avec aïoli."),
            ingredients: t("Gamba · alioli", "Prawn · aioli", "Crevette · aïoli"),
            allergens: allergenNotice,
            image: null,
          },
        ],
      },
      {
        id: "bocadillos",
        number: "06",
        label: t("Bocadillos", "Sandwiches", "Sandwichs"),
        title: t("Bocadillos", "Sandwiches", "Sandwichs"),
        note: t(
          "Todos los bocadillos: opción de pan sin gluten.",
          "All sandwiches: gluten-free bread option.",
          "Tous les sandwiches : option de pain sans gluten.",
        ),
        dishes: [
          {
            id: "bocadillo-tortilla",
            name: t("Tortilla al gusto", "Omelette sandwich", "Sandwich à l’omelette"),
            price: "8 €",
            description: t("Jamón, queso, chistorra, gamba, atún u otras opciones.", "Ham, cheese, chistorra, prawn, tuna or other options.", "Jambon, fromage, chistorra, crevette, thon ou autres options."),
            ingredients: t("Pan · tortilla · relleno a elegir", "Bread · omelette · choice of filling", "Pain · omelette · garniture au choix"),
            allergens: allergenNotice,
            image: null,
          },
          {
            id: "bocadillo-verduras",
            name: t("Verduras a la brasa", "Grilled vegetables", "Légumes grillés"),
            price: "8 €",
            description: t("Con queso brie.", "With Brie cheese.", "Avec brie."),
            ingredients: t("Pan · verduras a la brasa · queso brie", "Bread · grilled vegetables · Brie", "Pain · légumes grillés · brie"),
            allergens: allergenNotice,
            badge: "recommended",
            image: null,
          },
          {
            id: "bocadillo-panceta",
            name: t("Panceta adobada", "Marinated pork belly", "Poitrine de porc marinée"),
            price: "9 €",
            description: t("Con queso y pimiento verde.", "With cheese and green pepper.", "Avec fromage et poivron vert."),
            ingredients: t("Pan · panceta · queso · pimiento verde", "Bread · pork belly · cheese · green pepper", "Pain · poitrine de porc · fromage · poivron vert"),
            allergens: allergenNotice,
            image: null,
          },
          {
            id: "bocadillo-pechuga",
            name: t("Pechuga de pollo", "Chicken breast", "Blanc de poulet"),
            price: "9 €",
            description: t("Con queso, alioli y piquillos.", "With cheese, aioli and piquillo peppers.", "Avec fromage, aïoli et poivrons piquillo."),
            ingredients: t("Pan · pechuga · queso · alioli · piquillos", "Bread · chicken breast · cheese · aioli · piquillo peppers", "Pain · poulet · fromage · aïoli · piquillos"),
            allergens: allergenNotice,
            image: null,
          },
          {
            id: "bocadillo-lomo-panceta",
            name: t("Lomo y panceta adobada", "Pork loin and marinated belly", "Longe et poitrine de porc marinée"),
            price: "9 €",
            description: t("Con queso curado.", "With aged cheese.", "Avec fromage affiné."),
            ingredients: t("Pan · lomo · panceta · queso curado", "Bread · pork loin · pork belly · aged cheese", "Pain · longe de porc · poitrine · fromage affiné"),
            allergens: allergenNotice,
            image: null,
          },
          {
            id: "hamburguesa-mixta",
            name: t("Hamburguesa mixta", "Mixed burger", "Burger mixte"),
            price: "15 €",
            description: t("Con lechuga, tomate, queso curado, huevo y patatas.", "With lettuce, tomato, aged cheese, egg and fries.", "Avec laitue, tomate, fromage affiné, œuf et frites."),
            ingredients: t("Pan · carne · lechuga · tomate · queso · huevo · patatas", "Bread · meat · lettuce · tomato · cheese · egg · potatoes", "Pain · viande · laitue · tomate · fromage · œuf · pommes de terre"),
            allergens: allergenNotice,
            image: null,
          },
          {
            id: "calamares-bravos",
            name: t("Calamares bravos", "Spicy squid sandwich", "Sandwich de calamars relevés"),
            price: "11 €",
            description: t("A elegir entre alioli, mayonesa o salsa picante.", "Choose aioli, mayonnaise or spicy sauce.", "Au choix : aïoli, mayonnaise ou sauce piquante."),
            ingredients: t("Pan · calamares · salsa a elegir", "Bread · squid · choice of sauce", "Pain · calamars · sauce au choix"),
            allergens: allergenNotice,
            image: null,
          },
        ],
      },
      {
        id: "postres",
        number: "07",
        label: t("Postres", "Desserts", "Desserts"),
        title: t("Postres", "Desserts", "Desserts"),
        dishes: [
          {
            id: "torrija",
            name: t("Torrija de brioche", "Brioche French toast", "Pain perdu brioché"),
            price: "6,50 €",
            description: t("Con helado de galleta.", "With biscuit ice cream.", "Avec glace au biscuit."),
            ingredients: t("Brioche · helado de galleta", "Brioche · biscuit ice cream", "Brioche · glace au biscuit"),
            allergens: allergenNotice,
            image: null,
          },
          {
            id: "coulant",
            name: t("Coulant con helado", "Chocolate fondant with ice cream", "Coulant avec glace"),
            price: "6,50 €",
            description: t("Sabores a consultar.", "Ask about available flavours.", "Parfums disponibles à consulter."),
            ingredients: t("Coulant · helado", "Chocolate fondant · ice cream", "Coulant · glace"),
            allergens: allergenNotice,
            image: null,
          },
          {
            id: "cremoso-queso",
            name: t("Cremoso de queso", "Creamy cheesecake", "Crémeux au fromage"),
            price: "4 €",
            description: t("Con frutos rojos y lluvia de galleta Lotus.", "With red berries and Lotus biscuit crumble.", "Avec fruits rouges et éclats de biscuit Lotus."),
            ingredients: t("Queso · frutos rojos · galleta Lotus", "Cheese · red berries · Lotus biscuit", "Fromage · fruits rouges · biscuit Lotus"),
            allergens: allergenNotice,
            image: null,
          },
          {
            id: "cuajada",
            name: t("Cuajada de Ultzama", "Ultzama curd", "Caillé d’Ultzama"),
            price: "4 €",
            description: t("Con miel y nueces.", "With honey and walnuts.", "Avec miel et noix."),
            ingredients: t("Cuajada · miel · nueces", "Curd · honey · walnuts", "Caillé · miel · noix"),
            allergens: allergenNotice,
            image: null,
          },
          {
            id: "queso-irati",
            name: t("Queso de Irati", "Irati cheese", "Fromage d’Irati"),
            price: "6,50 €",
            description: t("Con membrillo y nueces.", "With quince paste and walnuts.", "Avec pâte de coing et noix."),
            ingredients: t("Queso de Irati · membrillo · nueces", "Irati cheese · quince paste · walnuts", "Fromage d’Irati · pâte de coing · noix"),
            allergens: allergenNotice,
            image: null,
          },
          {
            id: "fruta-temporada",
            name: t("Fruta de temporada", "Seasonal fruit", "Fruit de saison"),
            price: "3 €",
            description: t("Selección según temporada.", "Selection varies with the season.", "Sélection selon la saison."),
            ingredients: t("Fruta de temporada", "Seasonal fruit", "Fruit de saison"),
            allergens: allergenNotice,
            image: null,
          },
          {
            id: "mix-helados",
            name: t("Mix de bolas de helado", "Ice cream selection", "Assortiment de glaces"),
            price: "4 €",
            description: t("Selección de helados.", "A selection of ice creams.", "Assortiment de glaces."),
            ingredients: t("Helados · sabores a consultar", "Ice cream · ask about flavours", "Glaces · parfums à consulter"),
            allergens: allergenNotice,
            image: null,
          },
          {
            id: "sorbete-dia",
            name: t("Sorbete del día", "Sorbet of the day", "Sorbet du jour"),
            price: "4 €",
            description: t("Según temporada.", "Changes with the season.", "Selon la saison."),
            ingredients: t("Sorbete · sabor a consultar", "Sorbet · ask about flavour", "Sorbet · parfum à consulter"),
            allergens: allergenNotice,
            image: null,
          },
        ],
      },
    ],
  };

  // These are editorial working values until the kitchen validates each recipe.
  const cartaAllergens = {
    bravas: allergenSets.gluten,
    "rabas-chipiron": allergenSets.glutenMolluscs,
    chopitos: allergenSets.glutenMolluscs,
    padron: allergenSets.gluten,
    "jamon-iberico": allergenSets.glutenOption,
    chistorra: allergenSets.glutenFree,
    ajoarriero: allergenSets.glutenFishEgg,
    callos: allergenSets.glutenFree,
    "rabo-estofado": allergenSets.gluten,
    manitas: allergenSets.glutenEgg,
    entrecot: allergenSets.glutenOption,
    "chipirones-pelayo": allergenSets.glutenMolluscs,
    "pescado-fresco": allergenSets.fishGlutenFree,
    "ensalada-mixta": allergenSets.egg,
    "ensalada-chopitos": allergenSets.glutenEggMolluscs,
    "ensalada-cabra": allergenSets.dairyNuts,
    "huevos-foie": allergenSets.glutenOptionEggDairy,
    "huevos-patatas": allergenSets.glutenOptionEgg,
    "croqueta-jamon": allergenSets.glutenEggDairy,
    "frito-jamon-queso": allergenSets.glutenDairy,
    "frito-pimiento": allergenSets.gluten,
    "frito-calamar": allergenSets.glutenMolluscs,
    "frito-gamba": allergenSets.glutenCrustaceansEgg,
    "bocadillo-tortilla": allergenSets.glutenEgg,
    "bocadillo-verduras": allergenSets.glutenDairy,
    "bocadillo-panceta": allergenSets.glutenDairy,
    "bocadillo-pechuga": allergenSets.glutenEggDairy,
    "bocadillo-lomo-panceta": allergenSets.glutenDairy,
    "hamburguesa-mixta": allergenSets.glutenEggDairy,
    "calamares-bravos": allergenSets.glutenEggMolluscs,
    torrija: allergenSets.glutenEggDairy,
    coulant: allergenSets.glutenEggDairy,
    "cremoso-queso": allergenSets.glutenDairy,
    cuajada: allergenSets.dairyNuts,
    "queso-irati": allergenSets.dairyNuts,
    "fruta-temporada": allergenSets.none,
    "mix-helados": allergenSets.dairy,
    "sorbete-dia": allergenSets.none,
  };

  window.cartaData.categories.forEach((category) => {
    category.dishes.forEach((dish) => {
      if (cartaAllergens[dish.id]) dish.allergens = cartaAllergens[dish.id];
    });
  });
})();
