(function () {
  const t = (es, en, fr) => ({ es, en, fr });
  const dish = (es, en, fr, allergensEs, allergensEn, allergensFr, extra) => ({
    name: t(es, en, fr),
    allergens: t(allergensEs, allergensEn, allergensFr),
    extra: extra || null,
  });

  const allergens = {
    glutenFreeMolluscsSulphites: t(
      "Sin gluten · Moluscos · Sulfitos",
      "Gluten-free · Molluscs · Sulphites",
      "Sans gluten · Mollusques · Sulfites",
    ),
    glutenFreeSulphites: t("Sin gluten · Sulfitos", "Gluten-free · Sulphites", "Sans gluten · Sulfites"),
    glutenOptionEggFish: t(
      "Opción sin gluten · Gluten · Huevo · Pescado",
      "Gluten-free option · Gluten · Egg · Fish",
      "Option sans gluten · Gluten · Œuf · Poisson",
    ),
    glutenEggDairy: t("Gluten · Huevo · Lácteos", "Gluten · Egg · Dairy", "Gluten · Œuf · Produits laitiers"),
    glutenDairy: t("Gluten · Lácteos", "Gluten · Dairy", "Gluten · Produits laitiers"),
    glutenOptionEggSulphites: t(
      "Opción sin gluten · Gluten · Huevo · Sulfitos",
      "Gluten-free option · Gluten · Egg · Sulphites",
      "Option sans gluten · Gluten · Œuf · Sulfites",
    ),
    glutenOptionSulphites: t(
      "Opción sin gluten · Gluten · Sulfitos",
      "Gluten-free option · Gluten · Sulphites",
      "Option sans gluten · Gluten · Sulfites",
    ),
    glutenEggSulphites: t("Gluten · Huevo · Sulfitos", "Gluten · Egg · Sulphites", "Gluten · Œuf · Sulfites"),
    fishEggSulphites: t("Pescado · Huevo · Sulfitos", "Fish · Egg · Sulphites", "Poisson · Œuf · Sulfites"),
    fishShellfishGlutenEggDairySulphites: t(
      "Pescado · Crustáceos · Gluten · Huevo · Lácteos · Sulfitos",
      "Fish · Crustaceans · Gluten · Egg · Dairy · Sulphites",
      "Poisson · Crustacés · Gluten · Œuf · Produits laitiers · Sulfites",
    ),
    fish: t("Pescado", "Fish", "Poisson"),
    eggDairyNuts: t(
      "Huevo · Lácteos · Frutos de cáscara",
      "Egg · Dairy · Tree nuts",
      "Œuf · Produits laitiers · Fruits à coque",
    ),
    dairyNuts: t("Lácteos · Frutos de cáscara", "Dairy · Tree nuts", "Produits laitiers · Fruits à coque"),
    glutenEggDairyNuts: t(
      "Gluten · Huevo · Lácteos · Frutos de cáscara",
      "Gluten · Egg · Dairy · Tree nuts",
      "Gluten · Œuf · Produits laitiers · Fruits à coque",
    ),
    sulphites: t("Sulfitos", "Sulphites", "Sulfites"),
  };

  const shared = {
    pochas: dish(
      "Pochas a la navarra con almejas y piparras",
      "Navarre-style white beans with clams and piparras",
      "Haricots blancs à la navarraise, palourdes et piparras",
      allergens.glutenFreeMolluscsSulphites.es,
      allergens.glutenFreeMolluscsSulphites.en,
      allergens.glutenFreeMolluscsSulphites.fr,
    ),
    vegetables: dish(
      "Verdura de temporada",
      "Seasonal vegetables",
      "Légumes de saison",
      allergens.glutenFreeSulphites.es,
      allergens.glutenFreeSulphites.en,
      allergens.glutenFreeSulphites.fr,
    ),
    ensaladilla: dish(
      "Ensaladilla rusa con grissines",
      "Russian salad with grissini",
      "Salade russe avec gressins",
      allergens.glutenOptionEggFish.es,
      allergens.glutenOptionEggFish.en,
      allergens.glutenOptionEggFish.fr,
    ),
    pasta: dish(
      "Pasta del día",
      "Pasta of the day",
      "Pâtes du jour",
      allergens.glutenEggDairy.es,
      allergens.glutenEggDairy.en,
      allergens.glutenEggDairy.fr,
    ),
    risotto: dish(
      "Risotto de hongos con Idiazábal y parmesano",
      "Wild mushroom risotto with Idiazábal and Parmesan",
      "Risotto aux champignons, Idiazábal et parmesan",
      allergens.glutenDairy.es,
      allergens.glutenDairy.en,
      allergens.glutenDairy.fr,
    ),
    gazpacho: dish(
      "Gazpacho con picatostes, ibérico y huevo duro",
      "Gazpacho with croutons, Ibérico ham and boiled egg",
      "Gaspacho, croûtons, jambon ibérique et œuf dur",
      allergens.glutenOptionEggSulphites.es,
      allergens.glutenOptionEggSulphites.en,
      allergens.glutenOptionEggSulphites.fr,
    ),
    oxtail: dish(
      "Rabo tradicional con patatas fritas",
      "Traditional oxtail with fries",
      "Queue de bœuf traditionnelle avec frites",
      allergens.glutenOptionSulphites.es,
      allergens.glutenOptionSulphites.en,
      allergens.glutenOptionSulphites.fr,
    ),
    trotters: dish(
      "Manitas deshuesadas crujientes",
      "Crispy boneless pig's trotters",
      "Pieds de porc désossés et croustillants",
      allergens.glutenEggSulphites.es,
      allergens.glutenEggSulphites.en,
      allergens.glutenEggSulphites.fr,
    ),
    ajoarriero: dish(
      "Ajoarriero con huevo a baja temperatura",
      "Ajoarriero cod with slow-cooked egg",
      "Morue ajoarriero avec œuf basse température",
      allergens.fishEggSulphites.es,
      allergens.fishEggSulphites.en,
      allergens.fishEggSulphites.fr,
    ),
    peppers: dish(
      "Pimientos rellenos de merluza y gambas",
      "Peppers stuffed with hake and prawns",
      "Poivrons farcis au merlu et aux crevettes",
      allergens.fishShellfishGlutenEggDairySulphites.es,
      allergens.fishShellfishGlutenEggDairySulphites.en,
      allergens.fishShellfishGlutenEggDairySulphites.fr,
    ),
    fish: dish(
      "Pescado fresco del día con panaderas",
      "Fresh fish of the day with sliced baked potatoes",
      "Poisson frais du jour avec pommes de terre boulangères",
      allergens.fish.es,
      allergens.fish.en,
      allergens.fish.fr,
    ),
    entrecote: dish(
      "Entrecot con piquillos y patatas caseras",
      "Entrecôte with piquillo peppers and homemade fries",
      "Entrecôte, poivrons piquillo et frites maison",
      allergens.glutenOptionSulphites.es,
      allergens.glutenOptionSulphites.en,
      allergens.glutenOptionSulphites.fr,
      t("Suplemento +7 €", "Supplement +€7", "Supplément +7 €"),
    ),
    cheesecake: dish(
      "Cremoso de queso con Lotus y frutos rojos",
      "Creamy cheesecake with Lotus biscuit and red berries",
      "Crémeux au fromage, biscuit Lotus et fruits rouges",
      allergens.eggDairyNuts.es,
      allergens.eggDairyNuts.en,
      allergens.eggDairyNuts.fr,
    ),
    cuajada: dish(
      "Cuajada de Ultzama con miel y nueces",
      "Ultzama curd with honey and walnuts",
      "Caillé d’Ultzama au miel et aux noix",
      allergens.dairyNuts.es,
      allergens.dairyNuts.en,
      allergens.dairyNuts.fr,
    ),
    torrija: dish(
      "Torrija con helado de galleta",
      "French toast with biscuit ice cream",
      "Pain perdu avec glace au biscuit",
      allergens.glutenEggDairy.es,
      allergens.glutenEggDairy.en,
      allergens.glutenEggDairy.fr,
    ),
    irati: dish(
      "Queso de Irati con membrillo y nueces",
      "Irati cheese with quince paste and walnuts",
      "Fromage d’Irati, pâte de coing et noix",
      allergens.dairyNuts.es,
      allergens.dairyNuts.en,
      allergens.dairyNuts.fr,
    ),
    brownie: dish(
      "Brownie con helado de avellana",
      "Brownie with hazelnut ice cream",
      "Brownie avec glace à la noisette",
      allergens.glutenEggDairyNuts.es,
      allergens.glutenEggDairyNuts.en,
      allergens.glutenEggDairyNuts.fr,
    ),
    sorbet: dish(
      "Sorbete de mandarina al patxarán",
      "Mandarin and patxarán sorbet",
      "Sorbet mandarine au patxarán",
      allergens.sulphites.es,
      allergens.sulphites.en,
      allergens.sulphites.fr,
    ),
  };

  window.siteData = {
    defaultLanguage: "es",
    languages: ["es", "en", "fr"],
    ui: {
      skip: t("Saltar al contenido", "Skip to content", "Aller au contenu"),
      languageLabel: t("Idioma", "Language", "Langue"),
      portalKicker: t("Cocina navarra · Pamplona", "Navarre cuisine · Pamplona", "Cuisine navarraise · Pampelune"),
      portalTitleTop: t("Tres formas.", "Three ways.", "Trois façons."),
      portalTitleBottom: t("Una mesa.", "One table.", "Une table."),
      portalCopy: t(
        "Elige cómo quieres descubrir Casa Paco.",
        "Choose how you want to discover Casa Paco.",
        "Choisissez comment découvrir Casa Paco.",
      ),
      experiencesLabel: t("Experiencias de Casa Paco", "Casa Paco experiences", "Expériences Casa Paco"),
      navigationLabel: t("Navegación de Casa Paco", "Casa Paco navigation", "Navigation Casa Paco"),
      facadePhotoLabel: t(
        "Fachada de Casa Paco en Pamplona",
        "Casa Paco exterior in Pamplona",
        "Façade de Casa Paco à Pampelune",
      ),
      carta: t("Carta", "À la carte", "Carte"),
      daily: t("Menú del día", "Weekday menu", "Menu du jour"),
      weekend: t("Menú fin de semana", "Weekend menu", "Menu du week-end"),
      weekendShort: t("Fin de semana", "Weekend", "Week-end"),
      cartaMeta: t("Todo el año", "All year round", "Toute l’année"),
      dailyMeta: t("Martes a viernes · 22 €", "Tuesday to Friday · €22", "Du mardi au vendredi · 22 €"),
      weekendMeta: t("Sábados y domingos · 37 €", "Saturday and Sunday · €37", "Samedi et dimanche · 37 €"),
      reservations: t("Reservas", "Bookings", "Réservations"),
      dailyConditionsLabel: t("Condiciones del menú", "Menu conditions", "Conditions du menu"),
      breadExtra: t("Pan extra · 1 €", "Extra bread · €1", "Pain supplémentaire · 1 €"),
      terraceService: t("Servicio de terraza · 1 €", "Terrace service · €1", "Service en terrasse · 1 €"),
      halfMenu: t("Posibilidad de medio menú", "Half menu available", "Demi-menu disponible"),
      noSharing: t("No se permite compartir menú", "Menu cannot be shared", "Menu non partageable"),
      askAllergens: t(
        "Consulta al personal en caso de alergias",
        "Ask the team about allergies",
        "Consultez l’équipe en cas d’allergies",
      ),
      allergensTitle: t("Alérgenos", "Allergens", "Allergènes"),
      gluten: t("Gluten", "Gluten", "Gluten"),
      crustaceans: t("Crustáceos", "Crustaceans", "Crustacés"),
      egg: t("Huevo", "Egg", "Œuf"),
      fish: t("Pescado", "Fish", "Poisson"),
      dairy: t("Lácteos", "Dairy", "Produits laitiers"),
      nuts: t("Frutos de cáscara", "Tree nuts", "Fruits à coque"),
      sulphites: t("Sulfitos", "Sulphites", "Sulfites"),
      molluscs: t("Moluscos", "Molluscs", "Mollusques"),
      footer: t(
        "Casa Paco · Cocina navarra en Pamplona",
        "Casa Paco · Navarre cuisine in Pamplona",
        "Casa Paco · Cuisine navarraise à Pampelune",
      ),
    },
    menus: {
      "menu-del-dia": {
        eyebrow: t("Martes a viernes · Pamplona", "Tuesday to Friday · Pamplona", "Du mardi au vendredi · Pampelune"),
        title: t("Menú del día", "Weekday menu", "Menu du jour"),
        included: t(
          "Incluye pan, vino del año, sidra, refresco, caña o agua.",
          "Includes bread, house wine, cider, soft drink, small beer or water.",
          "Comprend pain, vin de l’année, cidre, boisson sans alcool, petite bière ou eau.",
        ),
        courses: [
          { title: t("Primeros", "Starters", "Entrées"), dishes: [shared.pochas, shared.vegetables, shared.ensaladilla, shared.pasta, shared.risotto, shared.gazpacho] },
          { title: t("Segundos", "Main courses", "Plats"), dishes: [shared.oxtail, shared.trotters, shared.ajoarriero, shared.peppers, shared.fish, shared.entrecote] },
          { title: t("Postres", "Desserts", "Desserts"), dishes: [shared.cheesecake, shared.cuajada, shared.torrija, shared.irati, shared.brownie, shared.sorbet] },
        ],
      },
      "menu-fin-de-semana": {
        eyebrow: t("Sábados y domingos · Navarra", "Saturday and Sunday · Navarre", "Samedi et dimanche · Navarre"),
        title: t("Menú fin de semana", "Weekend menu", "Menu du week-end"),
        included: t(
          "Incluye pan, vino crianza, sidra, refresco, caña o agua.",
          "Includes bread, crianza wine, cider, soft drink, small beer or water.",
          "Comprend pain, vin crianza, cidre, boisson sans alcool, petite bière ou eau.",
        ),
        courses: [
          {
            title: t("Primeros", "Starters", "Entrées"),
            dishes: [
              shared.pochas,
              shared.vegetables,
              shared.ensaladilla,
              shared.pasta,
              dish("Crepe de boletus con salsa trufada", "Boletus crêpe with truffle sauce", "Crêpe aux cèpes, sauce truffée", allergens.glutenDairy.es, allergens.glutenDairy.en, allergens.glutenDairy.fr),
              shared.risotto,
              shared.gazpacho,
            ],
          },
          {
            title: t("Segundos", "Main courses", "Plats"),
            dishes: [
              shared.oxtail,
              shared.trotters,
              shared.ajoarriero,
              shared.peppers,
              shared.fish,
              dish("Callos estilo navarro", "Navarre-style tripe", "Tripes à la navarraise", allergens.glutenFreeSulphites.es, allergens.glutenFreeSulphites.en, allergens.glutenFreeSulphites.fr),
              shared.entrecote,
            ],
          },
          {
            title: t("Postres", "Desserts", "Desserts"),
            dishes: [
              dish("Cremoso de queso con Lotus y frutos rojos", "Creamy cheesecake with Lotus biscuit and red berries", "Crémeux au fromage, biscuit Lotus et fruits rouges", allergens.glutenEggDairy.es, allergens.glutenEggDairy.en, allergens.glutenEggDairy.fr),
              shared.cuajada,
              shared.torrija,
              shared.irati,
              shared.brownie,
              shared.sorbet,
              dish("Goxua caramelizada casera", "Homemade caramelised goxua", "Goxua maison caramélisé", allergens.glutenEggDairy.es, allergens.glutenEggDairy.en, allergens.glutenEggDairy.fr),
            ],
          },
        ],
      },
    },
  };
})();
